### ISSUE TITLE
[Performance] Speed up Qwen 2 VL

### ISSUE THREAD

**Issue by awni** [Blaizzy/mlx-vlm#110]
This pattern of mixing in numpy and MLX inside the model forward will really slow things down. It forces a synchronization at each layer and breaks asynchronous evaluation:

https://github.com/Blaizzy/mlx-vlm/blob/main/mlx_vlm/models/qwen2_vl/language.py#L184-L185

Try to keep everything in MLX without converting to numpy in the `apply_multimodal_rotary_pos_emb` with only a small modification

```python
        if cache is not None:
            kv_seq_len += cache.offset + 1
            position_ids = mx.arange(cache.offset, cache.offset + L)
        else:
            position_ids = mx.arange(0, L)

        position_ids = mx.expand_dims(position_ids, axis=0)
        position_ids = mx.tile(position_ids, (3, 1, 1))
```

And in `apply_multimodal_rotary_pos_emb`, change:

```python
    mrope_section = np.cumsum(mrope_section * 2)[:-1].tolist()

    # position_ids = position_ids.tolist() <-- no need for that!
    cos = cos[position_ids]
    sin = sin[position_ids]

    cos = mx.concatenate(
        [m[i % 3] for i, m in enumerate(mx.split(cos, mrope_section, axis=-1))], axis=-1
    )[
        :, None, :, :
    ]  # unsqueeze dim 1
    sin = mx.concatenate(
        [m[i % 3] for i, m in enumerate(mx.split(sin, mrope_section, axis=-1))], axis=-1
    )[:, None, :, :]

    # Apply rotary embedding
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)

    return q_embed, k_embed # <-- no need to cast to `mx.array` as they are already `mx.array`
```

**Comment by awni** [comment]
Just FYI this change speeds up generation by 40% on an M2 Ultra:

```
mlx_vlm.generate --model mlx-community/Qwen2-VL-7B-Instruct-4bit --image ~/mlx-examples/stable_diffusion/still-life.png --prompt "Describe this please" --max-tokens 512
```

Pre: Generation: 55.160 tokens-per-sec

Post: Generation: 90.429 tokens-per-sec

**Comment by Blaizzy** [comment]
Thanks, will make the changes!

Btw I have been meaning to ask.

I can't reproduce this with `mx.where`. 

```python 
 def _merge_input_ids_with_image_features(
        self, image_features, inputs_embeds, input_ids
    ):
        image_token_index = self.config.image_token_index

        # Positions of <image> tokens in input_ids, assuming batch size is 1
        image_positions = input_ids == image_token_index
        image_indices = np.where(image_positions)[1].tolist()
        inputs_embeds[:, image_indices, :] = image_features.astype(mx.float32)

        # TODO: Add video features

        return inputs_embeds

```

**Comment by Blaizzy** [comment]
I face two errors.

1. Boolean indelicate are not yet supported 
2. Difference between `mx.where` and `np.where` usage throws errors because MLX expects another array besides the condition.

**Comment by awni** [comment]
We don't have a unary where or boolean indexing (for the same reason). More on why and possible work arounds [here](https://gist.github.com/awni/e20a288011adac0d0bdaf73e5296ca4f).

In your case it should be quite doable in MLX using either `__setitem__` with the right indices or `put_along_axis`. Could you share the shapes of `inputs_embeds`, `image_features` and `image_positions` and I will show you some example code for how to do it?

**Comment by Blaizzy** [comment]
Thanks, I will checkout! 

Here you go:

```
Input Embeddings Shape (1, 1220, 3584)
Image Features Shape (1, 1196, 3584)
Image Positions Shape (1, 1220)

```

**Comment by awni** [comment]
So I wrote a little to quickly that you can do it all in MLX. Actually you can do most of it in MLX but it should be ok from an efficiency standpoint if you are just a little careful. What I would do is make sure the `input_ids` are a Python list or Numpy array (an MLX array is also ok but it shouldn't be the output of a computation)

```
# Do this part in numpy. If `input_ids` is a python list or numpy array then you are good.
# if it's an MLX array then cast it to numpy before the `==` to avoid putting an op in the graph
input_positions = np.where(input_ids == image_token_index)
input_positions = tuple(map(mx.array, input_positions))

inputs_embeds = mx.zeros(shape=(1, 16, 4))
image_features = mx.random.uniform(shape=(1, 12, 4))

inputs_embeds[input_positions] = image_features
```

**Comment by Blaizzy** [comment]
Thanks!

If that's the case previous code is pretty close to this. Will run some benchmarks tho.

I wanted to move to `mx.where` instead of mixing numpy code as you suggested.

**Comment by awni** [comment]
The key is to avoid mixing numpy and MLX **inside** the graph. You can do preprocessing or postprocessing with numpy and that's usually fine. 

You just want to avoid having MLX OP -> numpy OP -> MLX OP because those cases will force a a synchronous graph evaluation which stalls the GPU and can really hit latency.

**Comment by Blaizzy** [comment]
Thanks!

I just made the changes you suggested and wow!
