### ISSUE TITLE
florence2 not work

### ISSUE THREAD

**Issue by cmgzy** [Blaizzy/mlx-vlm#119]
I run the code by command as:
`python -m mlx_vlm.generate --model mlx-community/Florence-2-large-ft-4bit --image ../playground/resized_image.jpg --prompt "[OD]"`

but error occurs:
`    PreNorm(None, DepthWiseConv2d(dim, 3, 1, 1), None) if conv_at_attn else None
  File "/Users/xx/miniforge3/lib/python3.10/site-packages/mlx_vlm/models/florence2/vision.py", line 114, in __init__
    self.dw = nn.Conv2d(
TypeError: Conv2d.__init__() got an unexpected keyword argument 'groups'`

mlx                          0.20.0
mlx-lm                       0.19.3
mlx-vlm                      0.1.0 (installed from git)

**Comment by Blaizzy** [comment]
Please install MLX from source 

```
pip install git+https://github.com/ml-explore/mlx.git
```

I just reached out to the team to release the version with support for grouped convolutions on pypi.

**Comment by cmgzy** [comment]
> Please install MLX from source
> 
> ```
> pip install git+https://github.com/ml-explore/mlx.git
> ```
> 
> I just reached out to the team to release the version with support for grouped convolutions on pypi.

It works. Also the latest mlx-0.21.0 works too as grouped convolution is supported.
FYI: Florence-2 run really fast on mlx🚀️ Nice work!

**Comment by Blaizzy** [comment]
My pleasure!


Indeed, it's quite fast.
