### ISSUE TITLE
SmolVLM-Instruct-4bit does not work in gradio UI

### ISSUE THREAD

**Issue by msurguy** [Blaizzy/mlx-vlm#131]
There's an error when uploading an image to chat while running `python3 -m mlx_vlm.chat_ui --model mlx-community/SmolVLM-Instruct-4bit`
Error: 
chat_ui.py", line 32, in chat
    if len(message.files) >= 1:
AttributeError: 'dict' object has no attribute 'files'

**Comment by Blaizzy** [comment]
please try using the chat in this PR: 

#75

**Comment by andimarafioti** [comment]
This is the PR https://github.com/Blaizzy/mlx-vlm/pull/96

**Comment by msurguy** [comment]
It works now, thanks!
