### ISSUE TITLE
Support for paligemma2

### ISSUE THREAD

**Issue by mseri** [Blaizzy/mlx-vlm#141]
I am adding it here as a ping. I ma not sure how different it is from paligemma. It has just been released: https://developers.googleblog.com/en/introducing-paligemma-2-powerful-vision-language-models-simple-fine-tuning/

**Comment by Blaizzy** [comment]
Thanks @mseri!

It's now supported :)

**Comment by mseri** [comment]
Thanks a lot! That was incredibly fast ⚡️

**Comment by Blaizzy** [comment]
The MLX King and the community move fast! 🚀
