### ISSUE TITLE
[Feature Request] Add support for OpenAI compatible API server

### ISSUE THREAD

**Issue by Extremys** [Blaizzy/mlx-vlm#20]
Hello @Blaizzy, it would be so great to have a similar OpenAI Compatible server like in https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/SERVER.md but supporting also image modality, what do you think?

**Comment by Blaizzy** [comment]
Hey @Extremys 

Thanks, that's a really good idea.

I'm already working on it and should be available soon, but it's still a private repo. 

Let me know if you want to help and I will add you there.

**Comment by Blaizzy** [comment]
@Extremys I built it :)

It's called FastMLX: 

https://github.com/Blaizzy/fastmlx
