### ISSUE TITLE
 Idefics2: Inconsistent converted model outputs and special token leakage

### ISSUE THREAD

**Issue by civvic** [Blaizzy/mlx-vlm#32]
I am encountering significant discrepancies in the outputs of two models when testing OCR that should theoretically perform similarly, as they share the same configuration. The first model is a pre-trained community model, and the second is a version I converted. Additionally, there's an issue with special tokens (<end_of_utterance>) not being filtered out in the outputs.  

Below are the details and comparisons of the outputs using both models. I've also noted the same behavior across different quantization settings. Could there be an underlying issue with the conversion process or the initial model weights that might explain these differences?

Consider the following snippet:  
```python
prompt_text = (
    "Do perform optical character recognition OCR on the image, which contains speech "
    "balloons from a comic book. The text is in English. Carefully extract the text exactly "
    "as it appears, ensuring that you preserve the original capitalization, punctuation, and "
    "formatting."
)

prompt = processor.apply_chat_template(resulting_messages, add_generation_prompt=True)

output = generate(
    model, processor, image, prompt,  # type: ignore
    verbose=True
)
```

Image:  
![PIKE_BOYLOVEGIRLS_T41_012_3_Default](https://github.com/Blaizzy/mlx-vlm/assets/1773683/9a4e249e-9b44-45ef-821b-db854761adfd)
but I've used many others.

Here are two different outputs using different models:

**Output 1 (Community Model):**
```bash
==========
Image: <PIL.PngImagePlugin.PngImageFile image mode=RGB size=185x145 at 0x55F1D7C10> 

Prompt: User:<image>Do perform optical character recognition OCR on the image, which contains speech balloons from a comic book. The text is in English. Carefully extract the text exactly as it appears, ensuring that you preserve the original capitalization, punctuation, and formatting.<end_of_utterance>
Assistant:
YOU'VE SEEMED SO UNHAPPY LATELY, CYNTHY! I WISH THERE WAS SOMETHING I COULD DO! I WISH YOU'D LET ME TRY AND MAKE YOU HAPPY!<end_of_utterance>
==========
Prompt: 112.710 tokens-per-sec
Generation: 27.255 tokens-per-sec
```

**Output 2 (My Converted Model):**
```bash
==========
Image: <PIL.PngImagePlugin.PngImageFile image mode=RGB size=185x145 at 0x55F1D7C10> 

Prompt: User:<image>Do perform optical character recognition OCR on the image, which contains speech balloons from a comic book. The text is in English. Carefully extract the text exactly as it appears, ensuring that you preserve the original capitalization, punctuation, and formatting.<end_of_utterance>
Assistant:
YOU'VE SEEMED LATELY, CYNTHY! "<end_of_utterance>
==========
Prompt: 60.653 tokens-per-sec
Generation: 27.033 tokens-per-sec
```

The only difference between the two runs is the model used:
- Output 1 uses the community model: `model_path = 'mlx-community/idefics2-8b-8bit'`
- Output 2 uses the model converted by me: `model_path = '../model/idefics2-8b-8bit'`

There are two issues:
1. Minor, the output does not filter out the special token `<end_of_utterance>`.
2. There is a significant difference in the quality of the outputs, which is curious given that both models use the same `config.json`. The conversion command used was:
   ```bash
   python -m mlx_vlm.convert --hf-path HuggingFaceM4/idefics2-8b --mlx-path model/idefics2-8b-8bit --q-bits 8 --quantize
   ```
   The quantization process in ML Core is a basic [affine quatization](https://apple.github.io/coremltools/docs-guides/source/quantization-overview.html), which should be deterministic. This leads me to suspect that the input weights might differ, although they shouldn't.

I've also tested other quantizations (4-bit and casting to `bfloat16`), and the (bad) outputs are consistently the same (`YOU'VE SEEMED LATELY, CYNTHY! "<end_of_utterance>` or very similar) across all quantizations, which differs substantially from the more accurate results I typically get with CUDA on Linux. This discrepancy might be due to the different quantization approaches between Hugging Face's BitsAndBytes and ML Core, but I didn't expect results so different.

Despite my efforts, I might be overlooking a simple explanation for these discrepancies. Could there be an aspect of the conversion process or setup that I'm missing? Any insights or suggestions would be greatly appreciated.

**Comment by Blaizzy** [comment]
The problem occurs because idefics 2 has `do_image_splitting` setting on the pre-processor set to `True`. This is useful for OCR on large images. This setting if `True`, each input image will be split into 4 sub-images, and concatenated with the original to form 5 images. 

My implemenation has this setting set to `False` because it slows down inference and for most images I tried, it worked fine without it :)

Just set it to `False` and it should work fine with your image

Check here: 

https://huggingface.co/mlx-community/idefics2-8b-4bit/blob/main/preprocessor_config.json#L3

**Comment by Blaizzy** [comment]
Regarding the `<end_of_utterance>`, this is a default token the model uses to simbolize end of chat response.

You can filter it.

https://huggingface.co/docs/transformers/main/en/model_doc/idefics2#usage-tips

**Comment by civvic** [comment]
> Just set it to `False` and it should work fine with your image
> 
Yeah, solved! Thank you for pointing that out! I typically set image splitting to false when testing with CUDA on my Linux setup and completely overlooked checking this setting on Mac. That was indeed the oversight on my part. I appreciate your help!

**Comment by civvic** [comment]
> Regarding the `<end_of_utterance>`, this is a default token the model uses to simbolize end of chat response.
> 
> You can filter it.
> 

I was just surprised by that. I suppose that HF Face handled the filtering automatically. I'll  do that. Thank you for the guidance!

**Comment by civvic** [comment]
BTW, PaliGemma works flawlessly. Amazing little model!

**Comment by Blaizzy** [comment]
> > Just set it to `False` and it should work fine with your image
> 
> Yeah, solved! Thank you for pointing that out! I typically set image splitting to false when testing with CUDA on my Linux setup and completely overlooked checking this setting on Mac. That was indeed the oversight on my part. I appreciate your help!

No worries. It's still a mystery to me how huggingface's models work regardless. I think they do extra padding.

**Comment by Blaizzy** [comment]
> > Regarding the `<end_of_utterance>`, this is a default token the model uses to simbolize end of chat response.
> > You can filter it.
> 
> I was just surprised by that. I suppose that HF Face handled the filtering automatically. I'll do that. Thank you for the guidance!

You can do the same in python script

**Comment by Blaizzy** [comment]
> BTW, PaliGemma works flawlessly. Amazing little model!

It's an amazing model, one of my favorites 🤩
