### ISSUE TITLE
Llava v1.6 support

### ISSUE THREAD

**Issue by jrp2014** [Blaizzy/mlx-vlm#42]
Which Llava models are supported? The mlx-examples repo supports only v1.5. Does this one support v1.6?  Does it generate keywords for an image , for example?

**Comment by Blaizzy** [comment]
Hey

As I mentioned earlier, Llava 1.6 (Next) support will be added soon.

At the moment we only support Llava 1.5.

Here is the list of models we plan to add soon:
https://github.com/Blaizzy/mlx-vlm/issues/39

**Comment by Blaizzy** [comment]
Could you elaborate on this keyword generation feature?

I couldn't find any information about it.
