### ISSUE TITLE
[Feature Request] Supports fine-tuning 

### ISSUE THREAD

**Issue by madroidmaq** [Blaizzy/mlx-vlm#49]

**Comment by Blaizzy** [comment]
Thanks @madroidmaq 

I'm working on it here: #41

**Comment by yukiarimo** [comment]
Any updates? Is it usable?

**Comment by Blaizzy** [comment]
It should be available soon.

**Comment by yukiarimo** [comment]
Cool! What models does it support? And is Pixtral is coming here?

**Comment by Blaizzy** [comment]
you can read more about the supported models here:
