### ISSUE TITLE
LLVM 1.6 is quite good, but could be better

### ISSUE THREAD

**Issue by jrp2014** [Blaizzy/mlx-vlm#52]
I have now managed to get LLAVA 1.6 running nicely on my MacBook Pro (M3 Max 48Gb).

```python
import mlx.core as mx
from mlx_vlm import load, generate

import os
from pathlib import Path

# model_path = "mlx-community/llava-1.5-7b-4bit"
model_path = "mlx-community/llava-v1.6-mistral-7b-8bit"
#model_path = "mlx-community/llava-v1.6-34b-8bit"
model, processor = load(model_path)

prompt = processor.tokenizer.apply_chat_template(
    [{"role": "user", "content": f"<image>\nProvide a formal caption and keywords for this image, suitable for microstock"}],
    tokenize=False,
    add_generation_prompt=True,
)

picpath = "/Users/home/Pictures/Processed"
pics = sorted(Path(picpath).iterdir(), key=os.path.getmtime, reverse=True)
pic = str(pics[0])
print(pic)


#output = generate(model, processor, "http://images.cocodataset.org/val2017/000000039769.jpg", prompt, verbose=True)
output = generate(model, processor, pic, prompt, max_tokens=200, verbose=True)

print(output)
```

Interestingly, the 34B and 7B+mistral models seem to produce almost the same result.  As the former is very much slower than the latter, you can guess which I use.

The generated keywords are limited; expanding the number of tokens you ask it generate just leads to repetition of generated keywords, rather than stopping.

If I try to generate keywords etc using Google services, this approach seems to generate more relevant keywords, including the mood of the picture, whereas the Google approach generates keywords such as "sky" or "vehicle registration", which are technically correct, but not generally really what the photo is about.

The development of models seems to be quite rapid at present.  Are any of the newer models better than LLaacn 1.6?

For example, do any models use GPS coordinates, or keywords that are already added?  (I usually include location data on photo ingestion).

**Comment by Blaizzy** [comment]
Hey @jrp2014 

Great to hear!

There are models better than llava 1.6 however, I don't know of any that use GPS coordinates. You can alternatively, finetune your own model.

**Comment by jrp2014** [comment]
What models do you reckon are better than llava 1.6?
