### ISSUE TITLE
load() pulling tokenizer instead of processor for deepseek

### ISSUE THREAD

**Issue by michaellee1** [Blaizzy/mlx-vlm#58]
Hi Blaizzy,

I've tried mlx-vlm with a few models that have worked great!  However, I'm now trying to run [deepseek-vl-1.3b-chat-4bit](https://huggingface.co/mlx-community/deepseek-vl-1.3b-chat-4bit), and I'm having a few issues.

## Reproduce

```
import mlx.core as mx
from mlx_vlm import load, generate

model_path = "mlx-community/deepseek-vl-1.3b-chat-4bit"
model, processor = load(model_path)
```

processor is loaded as a tokenizer, where
`type(processor)` yields `transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast`

## Next thoughts
I'm sure you know this way better than I do, but I dove in and it looks like the model card for deepseek doesn't have the same `auto_map` or processor script that, for example, does the [MLX Phi-3.5 Vision implementation](https://huggingface.co/mlx-community/Phi-3.5-vision-instruct-bf16/blob/main/processor_config.json), which it seems like both would be needed to load the processor.

## My next attempts
I started trying to get the processor from the original [deepcode HF](https://huggingface.co/deepseek-ai/deepseek-vl-1.3b-chat).  Obviously I knew I didn't want to just copy the implementation as they were using just plain torch while we want to use mpx.  But I thought maybe I could just plug and play the processor in the generate call

```
from deepseek_vl.models import VLChatProcessor
processor = VLChatProcessor.from_pretrained(model_path)

...(other code here)...

prompt = processor.tokenizer.apply_chat_template(
    [{"role": "user", "content": f"<image>\nWhat are these?"}],
    tokenize=False,
    add_generation_prompt=True,
)
output = generate(model, processor, "http://images.cocodataset.org/val2017/000000039769.jpg", prompt, verbose=True)
```
However, when I tried to use this processor instead in the generate() call, I am getting `TypeError: VLChatProcessor.__call__() takes 1 positional argument but 3 were given`, so my naive idea doesn't seem to work.

Any ideas here to fix?

**Comment by michaellee1** [comment]
@Blaizzy

**Comment by Blaizzy** [comment]
Hey @michaellee1 

Thanks for the patience! 

I have been caught up working on v0.1.0

You can find the solution here: 

https://github.com/Blaizzy/mlx-vlm/issues/46#issuecomment-2194031269
