### ISSUE TITLE
Qwen2-VL `lm_head` Weight Sanitization Prefixes

### ISSUE THREAD

**Issue by benzimring** [Blaizzy/mlx-vlm#61]
The [sanitize](https://github.com/Blaizzy/mlx-vlm/blob/37c3d4018bc48af40ad0bc2842140e77bad86c94/mlx_vlm/models/qwen2_vl/qwen2_vl.py#L141) method is modifying `"language_model.lm_head.*"` weight definitions twice, resulting in the following error:

```
ValueError: Received parameters not in model: language_language_model.model.language_model.lm_head.biases language_language_model.model.language_model.lm_head.scales language_language_model.model.language_model.lm_head.weight.
```

The embedded `transform_key` function should be changed to
```python
def transform_key(key):
    if "vision_tower" not in key:
        key = key.replace("visual", "vision_tower")
    if "language_model" not in key:
        if "model" in key:
            key = key.replace("model", "language_model.model")
        elif "lm_head" in key:
            key = key.replace("lm_head", "language_model.lm_head")
    return key
```

Creating a PR, and will update with the link

**Comment by benzimring** [comment]
Oops, looks like this issue was already known and a PR was just created, sorry @Blaizzy!

**Comment by Blaizzy** [comment]
This is cleaner tho, than my 2AM patch.

Let's rebase and merge it :)

**Comment by Blaizzy** [comment]
I'm making a new major release tomorrow for the trainer #41, so this will be included.

**Comment by Blaizzy** [comment]
No need to  be sorry, I love when the community contributes. This is our project!

**Comment by Blaizzy** [comment]
Can you make a PR with this elegant change?

**Comment by benzimring** [comment]
Absolutely, coming up!

**Comment by Blaizzy** [comment]
Perfect!
