### ISSUE TITLE
Please add support for Molmo

### ISSUE THREAD

**Issue by xSNYPSx** [Blaizzy/mlx-vlm#70]
This is SOTA open source models based on qwen2 vl - With unprecedented accuracy it can mark the coordinates of objects on screenshots, which distinguishes it from other VLMs. You can make amazing projects of autonomous computer control, but so far there is access only to FP-32 scales that simply do not fit into the RAM of even a 36GB Mac

**Comment by Blaizzy** [comment]
Awesome! 

Thanks for the suggestion, I will work on it after v0.1.0 that's coming out soon.

**Comment by mseri** [comment]
Any update on this?

**Comment by Blaizzy** [comment]
Yes.

Check #112

**Comment by Blaizzy** [comment]
I'm about to complete the language model and then will move to the vision model

**Comment by mseri** [comment]
Awesome, thank you so much!!!

**Comment by Blaizzy** [comment]
My pleasure!
