### ISSUE TITLE
Cannot install mlx-vlm because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by 111111111111111111111111111111111111110** [Blaizzy/mlx-vlm#74]
python --version
Python 3.11.2
pip --version
pip 23.0.1 from .../venv/lib/python3.11/site-packages/pip (python 3.11)

pip install mlx-vlm
Collecting mlx-vlm
  Downloading mlx_vlm-0.0.15-py3-none-any.whl (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.2/85.2 kB 1.3 MB/s eta 0:00:00
  Downloading mlx_vlm-0.0.14-py3-none-any.whl (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.1/85.1 kB 5.6 MB/s eta 0:00:00
  Downloading mlx_vlm-0.0.13-py3-none-any.whl (76 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.2/76.2 kB 8.6 MB/s eta 0:00:00
  Downloading mlx_vlm-0.0.12-py3-none-any.whl (76 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.2/76.2 kB 11.3 MB/s eta 0:00:00
  Downloading mlx_vlm-0.0.11-py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.9/75.9 kB 4.3 MB/s eta 0:00:00
  Downloading mlx_vlm-0.0.10-py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.8/75.8 kB 4.8 MB/s eta 0:00:00
  Downloading mlx_vlm-0.0.9-py3-none-any.whl (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.7/68.7 kB 3.9 MB/s eta 0:00:00
  Downloading mlx_vlm-0.0.8-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 3.8 MB/s eta 0:00:00
  Downloading mlx_vlm-0.0.7-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.8/46.8 kB 2.8 MB/s eta 0:00:00
  Downloading mlx_vlm-0.0.6-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.0/47.0 kB 2.8 MB/s eta 0:00:00
  Downloading mlx_vlm-0.0.5-py3-none-any.whl (39 kB)
  Downloading mlx_vlm-0.0.4-py3-none-any.whl (37 kB)
  Downloading mlx_vlm-0.0.3-py3-none-any.whl (29 kB)
  Downloading mlx_vlm-0.0.2-py3-none-any.whl (29 kB)
  Downloading mlx_vlm-0.0.1-py3-none-any.whl (29 kB)
ERROR: Cannot install mlx-vlm==0.0.1, mlx-vlm==0.0.10, mlx-vlm==0.0.11, mlx-vlm==0.0.12, mlx-vlm==0.0.13, mlx-vlm==0.0.14, mlx-vlm==0.0.15, mlx-vlm==0.0.2, mlx-vlm==0.0.3, mlx-vlm==0.0.4, mlx-vlm==0.0.5, mlx-vlm==0.0.6, mlx-vlm==0.0.7, mlx-vlm==0.0.8 and mlx-vlm==0.0.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    mlx-vlm 0.0.15 depends on mlx>=0.18.0
    mlx-vlm 0.0.14 depends on mlx>=0.14
    mlx-vlm 0.0.13 depends on mlx>=0.14
    mlx-vlm 0.0.12 depends on mlx>=0.14
    mlx-vlm 0.0.11 depends on mlx>=0.14
    mlx-vlm 0.0.10 depends on mlx>=0.14
    mlx-vlm 0.0.9 depends on mlx>=0.14
    mlx-vlm 0.0.8 depends on mlx>=0.14
    mlx-vlm 0.0.7 depends on mlx>=0.8.0
    mlx-vlm 0.0.6 depends on mlx>=0.8.0
    mlx-vlm 0.0.5 depends on mlx>=0.8.0
    mlx-vlm 0.0.4 depends on mlx>=0.8.0
    mlx-vlm 0.0.3 depends on mlx>=0.8.0
    mlx-vlm 0.0.2 depends on mlx>=0.8.0
    mlx-vlm 0.0.1 depends on mlx>=0.8.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by Blaizzy** [comment]
Hey @111111111111111111111111111111111111110 

Could you share the specs of your machine? 

Also, try installing mlx first

`pip install -U mlx mlx-vlm`

**Comment by 111111111111111111111111111111111111110** [comment]
oopsie its only for mac
who even reads intros
