### ISSUE TITLE
Getting 'NameError: name 'config' is not defined' when running example scripts

### ISSUE THREAD

**Issue by mark-lord** [Blaizzy/mlx-vlm#81]
Currently, I can run 

`python -m mlx_vlm.generate --model mlx-community/Qwen2-VL-2B-Instruct-4bit --max-tokens 100 --prompt "Compare these images" --image path/to/image1.jpg path/to/image2.jpg`

And it runs just fine. However, when I try to run the demo scripts in the readme.md, for example:

```
import mlx.core as mx
from mlx_vlm import load, generate
from mlx_vlm.prompt_utils import apply_chat_template

# Load the model
model_path = "mlx-community/Qwen2-VL-2B-Instruct-4bit"
model, processor = load(model_path)

# Prepare input
image = ["http://images.cocodataset.org/val2017/000000039769.jpg"]
prompt = "Describe this image."

# Apply chat template
formatted_prompt = apply_chat_template(
    processor, config, prompt, num_images=len(image)
)

# Generate output
output = generate(model, processor, image, formatted_prompt, verbose=False)
print(output)
```

Then I get 

```
(venv) (base) marklord@Marks-MacBook-Pro mlx-vlm % python generate.py 
Fetching 11 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 17075.26it/s]
Traceback (most recent call last):
  File "/Users/marklord/Documents/Dev/mlx-vlm/generate.py", line 15, in <module>
    processor, config, prompt, num_images=len(image)
               ^^^^^^
NameError: name 'config' is not defined
```

Figured it might be a dependency conflict as I'd installed MLX_VLM globally, so I made a venv, but I'm still getting the same behaviour.

Steps to recreate:

1. python -m venv venv; source venv/bin/activate
2. pip install mlx_vlm
3. save demo script from readme.md as generate.py
4. python generate.py

Also occurred for me if instead of step 2, you git clone the repo and pip install -e .

**Comment by mark-lord** [comment]
Was a simple enough fix! Just needed to add the import.

from mlx_vlm.utils import load_config

config = load_config(model_path)

Both demo scripts now working perfectly 😄

**Comment by Blaizzy** [comment]
Thanks a lot!
