### ISSUE TITLE
Video Input

### ISSUE THREAD

**Issue by chigkim** [Blaizzy/mlx-vlm#88]
Since there is capability for multi image input, is that possible to get video input as well?
Some VLMs support video like Qwen2-VL and MiniCPM-V 2.6.
Thanks!

**Comment by Blaizzy** [comment]
Thanks for the suggestions @chigkim!

This feature is already on the backlog as described here #75

**Comment by chigkim** [comment]
Sorry about that! I missed it.

**Comment by Blaizzy** [comment]
No worries!

It's great that you open this issue, it does bring the importance to light.

Could you comment in this PR #75 as well?
